version: '{build}'
branches:
  only:
    - master
clone_depth: 1
skip_non_tags: true
image: Visual Studio 2017
environment:
  nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - ps: |
  - npm i -g firebase-tools
build: "off"
test: "off"
cache:
  - '%APPDATA%\npm-cache'
deploy_script:
  - ps: |
      if ($env:firebase_token)
      {
        iex "firebase deploy --only hosting:myanmartools --token $env:firebase_token"
      }
