jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseNode@1
        inputs:
          version: '12.x'
        displayName: 'Use Node 12.x'
      - script: |
          yarn install --frozen-lockfile
        displayName: 'Install dependencies'
      - script: |
          yarn build
        displayName: "Run build"
      - script: |
          yarn test -c=ci
        displayName: 'Run test'
      - script: |
          yarn lint
        displayName: 'Run linting'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'dist'
          targetPath: 'dist'
        displayName: 'Publish build artifacts'
      - task: PublishTestResults@2
        inputs:
          testRunTitle: zawgyi-unicode-converter
          searchFolder: $(System.DefaultWorkingDirectory)/dist/junit
          testResultsFormat: JUnit
          testResultsFiles: "**/TESTS*.xml"
        condition: succeededOrFailed()
        displayName: Publish test results
